"""Bake facade members in an independent Blender scene with parametric aperture landmarks."""
import json
from pathlib import Path

import bpy
import bmesh
from mathutils import Vector

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'out/facade_review'
OUT.mkdir(parents=True, exist_ok=True)
scene = bpy.data.scenes.new('Facade Members')
bpy.context.window.scene = scene
library = {}


def member(name, vertices, faces):
    data = bpy.data.meshes.new(name)
    data.from_pydata([(x, -z, y) for x, y, z in vertices], [], faces)
    data.update()
    bm = bmesh.new()
    bm.from_mesh(data)
    bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
    bmesh.ops.triangulate(bm, faces=list(bm.faces))
    bm.to_mesh(data)
    bm.free()
    obj = bpy.data.objects.new(name, data)
    scene.collection.objects.link(obj)
    obj['runtime_member'] = name
    library[name] = {
        'vertices': [round(c, 7) for v in data.vertices for c in (v.co.x, v.co.z, -v.co.y)],
        'faces': [i for face in data.polygons for i in face.vertices],
    }
    return obj


# The aperture stays at +/-0.5; only the rim landmarks stretch with wall-bay clearance.
vertices = []
for radius, z in [(0.6, -0.5), (0.5, -0.5), (0.6, 0.43), (0.58, 0.5), (0.52, 0.5), (0.5, 0.43)]:
    vertices.extend((x * radius, y * radius, z) for x, y in [(-1, -1), (1, -1), (1, 1), (-1, 1)])
faces = []
for a, b in [(0, 1), (0, 2), (2, 3), (3, 4), (4, 5), (5, 1)]:
    for i in range(4):
        j = (i + 1) % 4
        faces.append((a * 4 + i, a * 4 + j, b * 4 + j, b * 4 + i))
reveal = member('reveal', vertices, faces)

section = [(0.5, -0.5), (0.5, 0.4), (0.35, 0.5), (-0.5, 0.5),
           (-0.5, 0.2), (-0.25, 0.2), (-0.25, -0.5)]
n = len(section)
vertices = [(x, y, z) for x in [-0.5, 0.5] for y, z in section]
faces = [tuple(range(n - 1, -1, -1)), tuple(range(n, n * 2))]
faces.extend((i, (i + 1) % n, (i + 1) % n + n, i + n) for i in range(n))
eave = member('eave', vertices, faces)

target = ROOT / 'public/js/architectureExteriorMeshData.js'
target.write_text('// Generated by tools/facade_authoring/author.py; edit the Blender source generator.\n'
                  + 'export const EXTERIOR_MESHES = Object.freeze('
                  + json.dumps(library, separators=(',', ':')) + ');\n', encoding='utf8')

mat = bpy.data.materials.new('Facade member stone')
mat.use_nodes = True
mat.diffuse_color = (0.42, 0.53, 0.58, 1)
bsdf = next(node for node in mat.node_tree.nodes if node.type == 'BSDF_PRINCIPLED')
next(s for s in bsdf.inputs if s.identifier == 'Base Color').default_value = mat.diffuse_color
next(s for s in bsdf.inputs if s.identifier == 'Roughness').default_value = 0.8
for obj, x in [(reveal, -1.1), (eave, 1.1)]:
    obj.location.x = x
    obj.data.materials.append(mat)
if bpy.context.screen:
    for area in bpy.context.screen.areas:
        if area.type == 'VIEW_3D':
            area.spaces.active.region_3d.view_location = (0, 0, 0)
            area.spaces.active.region_3d.view_distance = 5
            area.spaces.active.region_3d.view_rotation = Vector((3, -6, 3)).to_track_quat('Z', 'Y')
bpy.ops.wm.save_as_mainfile(filepath=str(OUT / 'facade_members.blend'), copy=True)
print(json.dumps({'scene': scene.name, 'members': {k: len(v['faces']) // 3 for k, v in library.items()},
                  'source': str(OUT / 'facade_members.blend'), 'runtime': str(target)}))
