"""Bake fitted engineering members in a separate scene; keep all user scenes intact."""
import json
import math
from pathlib import Path

import bpy
import bmesh
from mathutils import Vector

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'out/road_structure_review'
OUT.mkdir(parents=True, exist_ok=True)
scene = bpy.data.scenes.new('Road Engineering Members')
bpy.context.window.scene = scene
library = {}


def xyz(p):
    return (p[0], -p[2], p[1])


def mesh(name, vertices, faces):
    data = bpy.data.meshes.new(name)
    data.from_pydata([xyz(p) for p in vertices], [], faces)
    data.update()
    obj = bpy.data.objects.new(name, data)
    scene.collection.objects.link(obj)
    obj['runtime_member'] = name
    return obj


def prism(name, section, axis=2):
    vertices = []
    for end in [-.5, .5]:
        for a, b in section:
            vertices.append([a, b, end] if axis == 2 else [a, end, b])
    n = len(section)
    faces = [tuple(range(n - 1, -1, -1)), tuple(range(n, 2 * n))]
    faces += [(i, (i + 1) % n, (i + 1) % n + n, i + n) for i in range(n)]
    return mesh(name, vertices, faces)


def octagon(c=.08):
    return [(-.5 + c, -.5), (.5 - c, -.5), (.5, -.5 + c), (.5, .5 - c),
            (.5 - c, .5), (-.5 + c, .5), (-.5, .5 - c), (-.5, -.5 + c)]


def bake(obj):
    bm = bmesh.new()
    bm.from_mesh(obj.data)
    bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
    bmesh.ops.triangulate(bm, faces=list(bm.faces))
    bm.to_mesh(obj.data)
    bm.free()
    verts = [[v.co.x, v.co.z, -v.co.y] for v in obj.data.vertices]
    library[obj['runtime_member']] = {'vertices': [round(c, 7) for p in verts for c in p],
                         'faces': [i for p in obj.data.polygons for i in p.vertices]}


# Datum faces remain full size. Chamfers retreat into the existing collision envelope.
prism('portal_lintel', [(-.5, -.5), (.5, -.5), (.5, .36), (.42, .5), (-.42, .5), (-.5, .36)])
prism('portal_pillar', octagon(.055), 1)
prism('portal_wing', [(-.5, -.5), (.5, -.5), (.5, .45), (.36, .5), (-.36, .5), (-.5, .45)])
prism('gallery_column', octagon(.10), 1)
prism('crossbeam', [(-.5, -.30), (-.40, -.5), (.40, -.5), (.5, -.30), (.5, .5), (-.5, .5)])
prism('pier_cap', [(-.5, -.15), (-.30, -.5), (.30, -.5), (.5, -.15), (.5, .5), (-.5, .5)])
prism('platform_slab', [(-.5, -.34), (-.43, -.5), (.43, -.5), (.5, -.34), (.5, .5), (-.5, .5)])
prism('barrier', [(-.5, -.5), (.5, -.5), (.5, -.30), (.25, .06), (.20, .5),
                   (-.20, .5), (-.25, .06), (-.5, -.30)])
prism('crossing_base', octagon(.10), 1)
prism('crossing_head', octagon(.10))
prism('sign_post', octagon(.12), 1)
prism('sign_bracket', octagon(.08))
prism('lane_panel', octagon(.045))
prism('lane_hood', [(-.5, -.5), (.5, -.5), (.5, .2), (.43, .5), (-.43, .5), (-.5, .2)])
prism('lane_delineator', [(-.5, -.5), (.5, -.5), (.5, .36), (.28, .5), (-.28, .5), (-.5, .36)])
prism('lane_arrow', [(-.5, -.18), (.06, -.18), (.06, -.5), (.5, 0), (.06, .5), (.06, .18), (-.5, .18)])
prism('median_kerb', [(-.5, -.5), (.5, -.5), (.5, .30), (.30, .5), (-.30, .5), (-.5, .30)])
prism('signal_head', octagon(.08))
prism('signal_lens', [(math.cos(i * math.tau / 16) * .5, math.sin(i * math.tau / 16) * .5) for i in range(16)])
# The lower half stays open, unlike a solid box that hides the illuminated lens.
prism('signal_hood', [(-.5, -.5), (-.5, .30), (-.30, .5), (.30, .5), (.5, .30), (.5, -.5),
                      (.38, -.5), (.38, .25), (.25, .37), (-.25, .37), (-.38, .25), (-.38, -.5)])
# The corner profile is baked with the members so Blender and the runtime share the same curve.
corner = [[(1 - t) ** 2, t ** 2] for t in [i / 8 for i in range(9)]]
profile = mesh('junction_corner', [[-.5, 0, -.5]] + [[x - .5, 0, z - .5] for x, z in corner],
               [(0, i + 2, i + 1) for i in range(8)])
profile['profile_only'] = True
corner = [[round(v.co.x + .5, 7), round(-v.co.y + .5, 7)] for v in profile.data.vertices[1:]]
# Faceted circular pier with a recessed shaft and broad foot; all radii stay <= .5.
vertices = []
for y, radius in [(-.5, .5), (-.43, .5), (-.37, .42), (.38, .40), (.5, .43)]:
    for i in range(12):
        a = math.tau * i / 12
        vertices.append([math.cos(a) * radius, y, math.sin(a) * radius])
faces = [tuple(range(11, -1, -1)), tuple(range(48, 60))]
for j in range(4):
    for i in range(12):
        k = j * 12 + i
        faces.append((k, j * 12 + (i + 1) % 12, (j + 1) * 12 + (i + 1) % 12, k + 12))
mesh('bridge_pier', vertices, faces)
for obj in list(scene.objects):
    if not obj.get('profile_only'):
        bake(obj)
target = ROOT / 'public/js/roadStructureMeshData.js'
target.write_text('// Generated by tools/road_structure_authoring/author.py. Do not edit.\n'
                  + 'export const ROAD_STRUCTURE_MESHES = Object.freeze('
                  + json.dumps(library, separators=(',', ':')) + ');\n'
                  + 'export const ROAD_JUNCTION_PROFILE = Object.freeze('
                  + json.dumps({'corner': corner, 'cornerRadius': 2.4, 'taperSlope': .16,
                                'taperMin': 12, 'taperMax': 36}, separators=(',', ':')) + ');\n', encoding='utf8')
bpy.data.libraries.write(str(OUT / 'members.blend'), {scene})
print(json.dumps({'members': len(library), 'triangles': sum(len(v['faces']) // 3 for v in library.values()),
                  'scene': scene.name, 'output': str(target)}))
