// Run the authority path, not a duplicate damage formula: fire gates, AoE, snapshots, and rubble collision.
import assert from 'node:assert/strict';
import { BattleSim } from '../server/sim.js';
import { MAPGEO, CHARACTERS, heroWeapon, vsMult } from '../public/js/data.js';
import { MAP_BUILDING, buildingDistance, buildingRoofIndex, buildingRayHit } from '../public/js/mapBuilding.js';
import { readSrc, grabFn } from './audit_src.mjs';

const config = new Function('MAPGEO',`${grabFn(readSrc('test','e2e.mjs'),'fakeBattleConfig')}; return fakeBattleConfig(1);`)(MAPGEO);
const sim = new BattleSim(config);
sim.ents.clear(); sim.camps=[];
const wall = (x,z,hw,hd,key) => [x,z,Math.hypot(hw,hd),12,hw,hd,0,key,0];
const outer = [[-5,-5],[5,-5],[5,5],[-5,5]];
sim.setWorld({ occ: [wall(-5,0,.2,5,'house'),wall(5,0,.2,5,'house'),wall(0,-5,5,.2,'house'),wall(0,5,5,.2,'house'),wall(20,0,2,2,'behind'),
  [2,3,1,4,1,1,0,{},0], [2,3,1,4,1,1,0,'invalid',NaN]],
  roofs:[{buildingKey:'house',y:12,outer,holes:[]},{buildingKey:'house',y:Infinity,outer,holes:[]}] });
assert.equal(sim.mapBuildings.size,2);
const house=sim.ents.get('building:house'), behind=sim.ents.get('building:behind');
assert.ok(house.maxHp>0);
house.hp=0.1;
assert.equal(sim.snapshot().mb[0][1],1,'positive HP cannot serialize as terminal rubble');
house.hp=house.maxHp;
assert.equal(house.roofs.length,1);
assert.deepEqual(sim.snapshot().mb,[]);
assert.ok(!sim.snapshot().ents.some(e=>e.k==='mapbuilding'));
const character=Object.keys(CHARACTERS).find(id=>heroWeapon(id,'light')?.rate);
assert.ok(character);
const h=sim.addHero(CHARACTERS[character].side || 'SWARM','builder-test',character);
h.x=-20; h.z=0; h.y=0; h.ay=2;
sim.t=5;
const before=house.hp;
sim.heroHit(h.pid,house.id,'light');
assert.ok(house.hp<before,'wall hit reaches server damage settlement');
const once=house.hp;
sim.heroHit(h.pid,house.id,'light');
assert.equal(house.hp,once,'repeated same-tick report cannot bypass fire gate');
assert.ok(sim.snapshot().mb.some(([key,hp])=>key==='house' && hp<house.maxHp));
assert.equal(sim._losBlocked(-20,0,2,20,0,2,h,behind),true,'other buildings still block fire');
assert.equal(sim._losBlocked(-20,0,2,0,0,2,h,house),false,'target wall does not block its own damage');
assert.equal(buildingDistance(house.boxes,0,0,12,house.roofs),0,'roof impact uses nearest surface');
assert.ok(sim._lanceHits(h,{type:'gun'},-20,0,2,1,0,0,20).some(hit=>hit.t===house),'analytic lance hits a map wall');
sim._blast(h,{r:2,dmg:50,pen:20},0,0,12,null,false,50);
assert.ok(house.hp<once,'roof AoE damages its owner');
const roofHit=buildingRoofIndex([{buildingKey:'court',y:10,outer,holes:[[[-1,-1],[1,-1],[1,1],[-1,1]]]}]);
assert.equal(roofHit(0,20,0,0,0,0),null,'courtyard remains open');
assert.ok(roofHit(3,20,0,3,0,0),'roof blocks downward fire');
assert.ok(roofHit(3,0,0,3,20,0),'roof blocks upward fire');
assert.equal(buildingRayHit(house.boxes,0,20,0,0,0,0),null,'wall slabs do not fill courtyard volume');
assert.equal(vsMult({vs:{building:0.4}},'mapbuilding'),0.4,'building damage class is shared');
sim._damage(house,1e9,h,1e6);
assert.equal(house.hp,0);
assert.equal(house.collapsed,true);
assert.equal(house.roofs[0].y,12*MAP_BUILDING.RUBBLE_H);
assert.equal(sim._losBlocked(-20,0,8,20,0,8,h,behind),false,'collapse opens upper line of sight');
assert.equal(sim._losBlocked(-20,0,1,20,0,1,h,behind),true,'rubble still blocks ground shots');
const rubble=JSON.stringify(house.boxes);
sim._damage(house,100,h);
assert.equal(JSON.stringify(house.boxes),rubble,'duplicate destruction cannot shrink rubble twice');
assert.ok(sim.snapshot().mb.some(([key,hp])=>key==='house' && hp===0),'late join receives terminal state');
sim.setWorld({occ:[]});
assert.equal(house.hp,0,'world re-upload cannot restore HP');
sim.tick(0.125);
const raised = new BattleSim(config);
raised.ents.clear(); raised.camps=[];
raised.setWorld({occ:[[0,0,6,12,5,.2,Math.PI/4,'raised',100]]});
raised._hgtAt=()=>100;
assert.equal(raised._losBlocked(-20,0,2,20,0,2),true,'raised rotated wall blocks at its world height');
assert.equal(raised._losBlocked(-20,0,20,20,0,20),false,'ray above raised wall stays clear');
raised._kill(raised.ents.get('building:raised'));
assert.equal(raised._losBlocked(-20,0,8,20,0,8),false,'raised rubble opens the same upper band');
assert.equal(raised._losBlocked(-20,0,1,20,0,1),true,'raised rubble preserves its ground band');
console.log('Building damage authority: passed');
