// Execute accumulation, lifecycle and authority seams; fixed inputs isolate weather history.
import assert from 'node:assert/strict';
import { stepWeatherSurface, weatherSurfaceCover, lightningFireSeconds, lightningStatus, clearLightningScorch } from '../public/js/weatherState.js';
import { BattleSim } from '../server/sim.js';
import { MAPGEO, dayHourRate } from '../public/js/data.js';
import { readSrc, grabFn } from './audit_src.mjs';

const storm = { effectiveRain: 1, effectiveSnow: 1, effectiveSand: 1, wind: 100 };
const start = stepWeatherSurface();
assert.deepEqual(start, { water: 0, snow: 0, sand: 0 });
assert.equal(weatherSurfaceCover(stepWeatherSurface(start, storm, 1).water), 0);
const mature = stepWeatherSurface(start, storm, 300);
for (const key of Object.keys(start)) assert(mature[key] > .8);
let frames = start;
for (let i = 0; i < 18000; i++) frames = stepWeatherSurface(frames, storm, 1 / 60);
for (const key of Object.keys(start)) assert(Math.abs(frames[key] - mature[key]) < 1e-10);
const light = stepWeatherSurface(start, { effectiveRain: .25, effectiveSand: .25 }, 300);
assert(light.water < mature.water && light.sand < mature.sand);
const calm = stepWeatherSurface(mature, {}, 60), windy = stepWeatherSurface(mature, { wind: 100 }, 60);
assert(windy.sand < calm.sand && calm.snow < mature.snow && calm.water < mature.water);
assert.deepEqual(stepWeatherSurface(mature, storm, NaN), mature);
assert(Math.abs(lightningFireSeconds() * dayHourRate() - 24) < 1e-10);
const unit = { hp: 70, maxHp: 100, buffs: { old: 30 }, slowUntil: 20 };
const scorch = () => { unit.lightningScorch = { hp: unit.hp, states: lightningStatus(unit, 5) }; };
scorch(); clearLightningScorch(unit, 6); assert(unit.lightningScorch);
unit.hp = 60; clearLightningScorch(unit, 7); assert(unit.lightningScorch);
unit.hp = 61; clearLightningScorch(unit, 8); assert(!unit.lightningScorch);
scorch(); unit.buffs.new = 40; clearLightningScorch(unit, 9); assert(!unit.lightningScorch);
scorch(); unit.slowUntil = 45; clearLightningScorch(unit, 10); assert(!unit.lightningScorch);
scorch(); unit.hp = 100; clearLightningScorch(unit, 11); assert(!unit.lightningScorch);
unit.hp = 50; scorch(); unit.dead = true; clearLightningScorch(unit, 12); assert(!unit.lightningScorch);
unit.dead = false; scorch(); unit.stealthUntil = 80; clearLightningScorch(unit, 13); assert(!unit.lightningScorch);
scorch(); clearLightningScorch(unit, 90); assert(unit.lightningScorch, 'Expiry alone is not a newly acquired state');

const config = new Function('MAPGEO', `${grabFn(readSrc('test', 'e2e.mjs'), 'fakeBattleConfig')}; return fakeBattleConfig(1);`)(MAPGEO);
const sim = new BattleSim(config);
sim.ents.clear(); sim._fires = []; sim._allBodies = () => [];
sim.bounds = { minX: -50, maxX: 50, minZ: -50, maxZ: 50 };
sim._hgtGrid = { minX: -100, minZ: -100, cell: 100, cols: 2, rows: 2, data: new Float32Array(4) };
sim._wetGrid = { ...sim._hgtGrid, data: new Uint8Array(4) };
sim.worldOcc = []; sim.curWeatherDyn = {};
sim._strikeWeatherSurface(() => .5);
assert.equal(sim._fires.length, 1);
assert.equal(sim.weatherScars.length, 1);
const fire = sim._fires[0];
sim._tickHazards(lightningFireSeconds() - 1); assert(sim.ents.has(fire.id));
sim._tickHazards(1); assert(!sim.ents.has(fire.id));
assert.equal(sim.weatherScars.length, 1, 'Extinction preserves the scar');
sim._strikeWeatherSurface(() => .5);
sim.curWeatherDyn = { effectiveRain: .01 };
sim._tickHazards(.1); assert.equal(sim._fires.length, 0);
sim.curWeatherDyn = {}; sim._tickHazards(.1); assert.equal(sim._fires.length, 0, 'Dry weather cannot reignite old fires');
sim._strikeWeatherSurface(() => .5); sim.curWeatherDyn = { effectiveSnow: .1 };
sim._tickHazards(.1); assert.equal(sim._fires.length, 0);
sim._strikeWeatherSurface(() => .5); assert.equal(sim._fires.length, 0, 'Precipitation prevents ignition');
sim.curWeatherDyn = {}; sim._wetGrid.data.fill(1);
sim._strikeWeatherSurface(() => .8); assert.equal(sim._fires.length, 0, 'Water cannot ignite');
sim._wetGrid.data.fill(0); sim.worldOcc = [[0, 0, 10, 30]];
sim._strikeWeatherSurface(() => .5); assert.equal(sim._fires.length, 0, 'Solid objects receive a local mark instead of ground fire');
assert.equal(sim.weatherScars.at(-1).y, 30);
sim._markWeatherScorch(0, 30, 0);
assert.equal(sim.weatherScars.length, 2, 'Repeated strikes retain one footprint');
sim.worldOcc = []; sim._hgtGrid.data.set([0, 100, 0, 100]);
sim._strikeWeatherSurface(() => .5); assert.equal(sim._fires.length, 0, 'Steep terrain cannot ignite a flat fire patch');
sim._hgtGrid.data.fill(0); sim._ingestSlabs({ slabs: [[-20, 0, 20, 0, 8, 1]] });
sim._strikeWeatherSurface(() => .5); assert.equal(sim._fires.length, 0, 'Unknown elevated deck height cannot ignite ground below it');
sim._slabGrid = null; sim._hgtGrid = null;
sim._strikeWeatherSurface(() => .5); assert.equal(sim._fires.length, 0, 'Missing terrain data omits ignition');
const rejoin = JSON.parse(JSON.stringify(sim.snapshot()));
assert.deepEqual(rejoin.weatherScars, sim.weatherScars);
assert.deepEqual(rejoin.weatherSurface, sim.weatherSurface);
sim._tickN = 1;
assert(sim.snapshotFor('STEEL').weatherScars);
assert.equal(sim.snapshotFor('STEEL').weatherScars, undefined, 'Unchanged scars do not repeat every tick');
sim._tickN = 32;
assert.deepEqual(sim.snapshotFor('STEEL').weatherScars, sim.weatherScars, 'Periodic baselines restore late joiners');
console.log('Weather accumulation, frame independence, recovery, permanent scars, rejoin and authoritative fire lifecycle passed.');
