import { existsSync, readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { spawn } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CHARACTERS, heroWeapon } from '../../public/js/data.js';
import { characterCombatStyle } from '../../public/js/characterStyle.js';
import { blenderMcp } from './mcp.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const foundation = path.join(process.env.ProgramFiles || 'C:/Program Files', 'Blender Foundation');
const installed = existsSync(foundation) ? readdirSync(foundation)
  .filter(name => name.startsWith('Blender ')).sort((a, b) => b.localeCompare(a, undefined, { numeric: true }))
  .map(name => path.join(foundation, name, 'blender.exe')).find(existsSync) : null;
const blender = process.env.BLENDER_BIN || installed || 'blender';
const args = process.argv.slice(2), selector = args.indexOf('--asset');
const useMcp = args.includes('--mcp'), combat = args.includes('--combat');
const requested = selector < 0 ? 'all' : args[selector + 1];
const contractArg = args.indexOf('--contract');
const contractFile = contractArg < 0 ? 'assets.json' : args[contractArg + 1];
const promptArg = args.indexOf('--user-prompt');
const userPrompt = promptArg < 0
  ? contractFile === 'factions.json' ? 'Author faction models and articulated combat presentation in Blender'
    : 'Author integrated combat effects on this mech through the canonical Blender recipe'
  : args[promptArg + 1];
const contract = JSON.parse(readFileSync(path.join(root, 'tools/mech_authoring', contractFile), 'utf8'));
const ids = requested === 'all' ? Object.keys(contract.assets) : requested.split(',');
if (ids.some(id => !contract.assets[id])) throw new Error(`Unknown asset: ${requested}`);
const flags = args.filter((value, i) => value !== '--mcp'
  && (selector < 0 || (i !== selector && i !== selector + 1))
  && (promptArg < 0 || (i !== promptArg && i !== promptArg + 1)));
if (combat) {
  const directory = path.join(root, 'out/combat_reference');
  mkdirSync(directory, { recursive: true });
  const intent = Object.fromEntries(Object.keys(CHARACTERS).map(id => [id, {
    ...characterCombatStyle(id), weapons: Object.fromEntries(['light', 'heavy'].map(slot => {
      const weapon = heroWeapon(id, slot);
      return [slot, { type: weapon.type, charge: weapon.charge, fan: weapon.fan, rate: weapon.rate }];
    })),
  }]));
  const file = path.join(directory, 'intent.json');
  writeFileSync(file, JSON.stringify(intent));
  flags.push('--combat-data', file);
}
// A factory process per asset prevents unused datablocks and previous actions entering the editable source.
for (const id of ids) {
  if (useMcp) {
    const script = path.join(root, 'tools/mech_authoring/build.py');
    const code = contract.authoring.factoryWorker
      ? `import bpy, subprocess\nr = subprocess.run([bpy.app.binary_path, '--background', '--factory-startup', '--python-exit-code', '1', '--python', ${JSON.stringify(script)}, '--', '--asset', ${JSON.stringify(id)}, *${JSON.stringify(flags)}], capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=240, creationflags=getattr(subprocess, 'CREATE_NO_WINDOW', 0))\nif r.returncode: raise RuntimeError(r.stdout[-3000:] + r.stderr[-3000:])\nprint(next(line for line in r.stdout.splitlines() if line.startswith('ASSET_RESULT ')))`
      : `import runpy, sys\nsys.argv = ['build.py', '--', '--asset', ${JSON.stringify(id)}, *${JSON.stringify(flags)}]\nrunpy.run_path(${JSON.stringify(script)}, run_name='__main__')`;
    const result = await blenderMcp('execute_blender_code', { code, user_prompt: userPrompt });
    for (const item of result.content || []) if (item.type === 'text') {
      if (/Traceback|Error executing|error_type/.test(item.text)) throw new Error(item.text);
      console.log(item.text.split('\n').find(line => line.startsWith('ASSET_RESULT ')) || `Authored ${id}`);
    }
    continue;
  }
  const processArgs = ['--background', '--factory-startup', '--python-exit-code', '1',
    '--python', path.join(root, 'tools/mech_authoring/build.py'), '--', '--asset', id, ...flags];
  const code = await new Promise((resolve, reject) => {
    const child = spawn(blender, processArgs, { cwd: root, stdio: 'inherit', windowsHide: true });
    child.on('error', reject); child.on('exit', code => resolve(code ?? 1));
  });
  if (code) { process.exitCode = code; break; }
}
if (combat && !process.exitCode) {
  const roster = Object.keys(CHARACTERS).filter(id => existsSync(path.join(root, 'public/js/forge/combatAssets', id + '.js')));
  const source = '// Generated by tools/mech_authoring/build.mjs.\n'
    + roster.map(id => `import ${id} from './combatAssets/${id}.js';`).join('\n')
    + `\nexport const COMBAT_ASSETS = { ${roster.join(', ')} };\n`;
  writeFileSync(path.join(root, 'public/js/forge/combatAssets.js'), source);
}
if (contract.authoring.registry && !process.exitCode && !args.includes('--rebuild')) {
  const runtime = path.resolve(root, 'tools/mech_authoring', contract.authoring.runtime);
  const registry = path.resolve(root, 'tools/mech_authoring', contract.authoring.registry);
  const roster = Object.keys(contract.assets).filter(id => existsSync(path.join(runtime, id + '.js')));
  const relative = path.relative(path.dirname(registry), runtime).replaceAll('\\', '/');
  writeFileSync(registry, '// Generated by tools/mech_authoring/build.mjs.\n'
    + roster.map(id => `import ${id} from './${relative}/${id}.js';`).join('\n')
    + `\nexport const ${contract.authoring.registryExport} = { ${roster.join(', ')} };\n`);
}
